### PR TITLE
Fixes #262 downstream.sh README page edits

### LINKED ISSUE #262: downstream build script creates a nonsensical sentence in the README
##### SUMMARY

The downstream build script replaces all occurrences of community.kubernetes with kubernetes.core, but it creates this nonsensical sentence in the README: "This repo hosts the kubernetes.core (a.k.a. kubernetes.core) Ansible Collection."

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

README (kubernetes.core)

##### ADDITIONAL INFORMATION

https://galaxy.ansible.com/kubernetes/core

### PR DESCRIPTION
**Pull request by tima**

### CODE REVIEW

**Review by maxamillion — APPROVED** [review]

File: utils/downstream.sh [hunk 1]
```diff
@@ -72,6 +72,7 @@ f_text_sub()
     sed -i.bak "s/namespace\:.*$/namespace: kubernetes/" "${_build_dir}/galaxy.yml"
     sed -i.bak "s/^version\:.*$/version: ${DOWNSTREAM_VERSION}/" "${_build_dir}/galaxy.yml"
     find "${_build_dir}" -type f -exec sed -i.bak "s/community\.kubernetes/kubernetes\.core/g" {} \;
+    sed -i "s/a\.k\.a\. \`kubernetes\.core\`/formerly known as \`community\.kubernetes\`/" "${_build_dir}/README.md";
```
Comment (geerlingguy) [inline utils/downstream.sh:75]: Needed a `.bak` to work on macOS as well as Linux; I'll add in a follow-up.
